# Computing normalized values

We create a `SummarizedExperiment` that contains the normalized expression values from `edgeR::cpm()`.
This is typically useful for visualizing the expression profiles of the top DE genes.

```{r}
norm.se <- se
SummarizedExperiment::rowData(norm.se)$retained <- seq_len(nrow(norm.se)) %in% y$genes$origin
norm.se$lib.size <- y$samples$lib.size
norm.se$norm.factors <- y$samples$norm.factors
SummarizedExperiment::assay(norm.se, "logCPM") <- edgeR::cpm(
    as.matrix(SummarizedExperiment::assay(norm.se, <%= ASSAY %>)), 
    lib.size=norm.se$lib.size, 
    norm.factors=norm.se$norm.factors,
    log=TRUE
)
```

And we save it.

```{r save-norm}
norm.meta <- list(
    title='Normalized RNA-seq data',
    authors=<%= AUTHOR %>,
    type="summarized_experiment",
:BEGIN subset-metadata
    summarized_experiment=list(
        subset=subset.meta
    )
:END
)

augere.core::saveResult(
    norm.se,
    file.path(result.dir, "normalized"), 
:BEGIN merge-metadata
    metadata=c(common.meta, norm.meta)
:END
:BEGIN no-merge-metadata
    metadata=norm.meta
:END
)
```

# Session information {-}

```{r}
sessionInfo()
```
